---
streams:
- topic: xmatch
  group_id: xmatch
  bootstrap_servers: kafka1,kafka2,kafka3
- topic: correcction
  group_id: correction
  bootstrap_servers: kafka1,kafka2,kafka3

slack:
  token: "token"
  signature: "signature"
