version: '3'
services:
    scheduled:
      build:
        context: .
        dockerfile: user_interface/slack/slack_bot/Dockerfile.schedule
      env_file:
        - .env
    commands:
      build:
        context: .
        dockerfile: user_interface/slack/slack_bot/Dockerfile.commands
      ports:
        - 8071:8071
      env_file:
        - .env
