FROM python:3.7
ENV TZ="America/Santiago"
COPY requirements.txt /app/requirements.txt


WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt
RUN pip install -r /app/user_interface/slack/slack_bot/requirements.txt

CMD ["python", "-m", "user_interface.slack.slack_bot.schedule.main"]
