FROM python:3.7
ENV TZ="America/Santiago"
COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && pip install gunicorn==19.9.0


WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt
RUN pip install -r /app/user_interface/slack/slack_bot/requirements.txt

EXPOSE 8082
CMD ["gunicorn", "-w", "1", "--threads", "3", "-b", "0.0.0.0:8071", "-t", "360", "user_interface.slack.slack_bot.commands.server:create_app()"]
