---
slack_bot:
  stage: testing
  log_level: develop
  slack_credentials:
    token: test_token
  reports:
    - name: detections_report
      database:
        # Add as many databases as you want to check
        # Keep in mind: One database entry per topic
        # For kafka topics use the streams field below
        - host: localhost
          database: postgres
          user: postgres
          password: postgres
          port: 5432
          detections_table_name: detection
          detections_id_field: candid
      streams:
        # Add as many kafka servers and topics you want to check
        # Keep in mind: One stream entry per topic
        - bootstrap_servers: localhost:9094
          group_id_format: "bot_%s"
          topic_format: "ztf_%s_test"
          date_format: "%Y%m%d"
          identifiers:
            - oid
            - candid
      batch_size: 1
    - name: lag_report
      streams:
        - bootstrap_servers: localhost:9094
          group_id: xmatch
          topic_format: ztf_%s_test
          date_format: "%Y%m%d"
    - name: stamp_classifications_report
      database:
        - host: localhost
          database: postgres
          user: postgres
          password: postgres
          port: 5432
          table_names: [probability, object]
          mjd_name: firstmjd
  schedule:
    - period: every_day
      report: lag_report
      channels:
        - test-bots
      times:
        - '12:00'
        - '16:00'
    - period: every_day
      report: detections_report
      channels:
        - test-bots
      times:
        - '16:00'
    - period: every_day
      report: stamp_classifications_report
      channels:
        - test-bots
      times:
        - '16:00'
        
        
